name = "mug"
version = "0.2.0"

description = "A TCP client for Gleam!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "mug" }
links = [{ title = "Website", href = "https://gleam.run" }]
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.31"
gleam_erlang = "~> 0.22"

[dev-dependencies]
gleeunit = "~> 1.0"
glisten = "~> 0.8"
gleam_otp = "~> 0.7"
